### ISSUE TITLE
Appium: How to select element on drawable canvas without help of attributes?

### ISSUE THREAD

**Issue by JaimishaPatel** [xmnfw/pywim#44]
I am using Appium for automated testing. I want to select an element on the drawable canvas. I know how to find an element by attributes. But I want to find an element on drawable canvas without the help of attributes.

Is there any possible way to achieve this?

**Comment by xmnlab** [comment]
hey @JaimishaPatel it seems your problem is not related to this project. maybe you should try the github of appium project https://github.com/appium/appium
