### ISSUE TITLE
In Firebase Testlab : XCTest is not working for iOS

### ISSUE THREAD

**Issue by harshmehta1995** [xmnfw/pywim#45]
I am attaching google drive link, please open it and download this file then upload it in for XC Test (https://drive.google.com/open?id=1KUuCm5WQ89AqDcvNimkIEJaxPkth5FFI)

I followed this link to make a build for iOS XCTest using this link provided by firebase https://firebase.google.com/docs/test-lab/ios/firebase-console?authuser=0

But it is not giving a result as expected

I am getting the following problem every time,

However, I get the issue: From the video recorded by Firebase Testlab, I can see that the app is installed on a device, but it is being opened and suddenly being closed.

Do you have any ideas what it could be?

**Comment by xmnlab** [comment]
@harshmehta1995 it seems your problem is not related to this project.
if you have any log (related to this project) please share that using a public service like pastebin or gist.
